title = '漢留雜誌'
defaultContentLanguage = 'zh'
languageCode = 'zh'
baseURL = 'https://example.org/'

[hankeep]
 [params.hankeep]
  sidePane = true
  countPageItems = 7 
  searchPath = 'search'
 [params.hankeep.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5
 [params.hankeep.side.home]
  sidePaneSticky = false 
  taxonomies = ['tags']
  taxonomyTitles = ['tags']
  countTaxonomy = 6
 [params.hankeep.side.list]
  sidePaneSticky = false
 [params.hankeep.side.single]
  sidePaneSticky = true 
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

[related]
 includeNewer = true
 [[related.indices]]
  name = 'tags'
  weight = 100

[taxonomies]
 tag = 'tags'

[params]
 summaryLength = 1

[params.links]
 hugo = 'https://gohugo.io/'
 theme = 'https://github.com/hankeep/hugo-theme-hankeep'

[[menus.main]]
 name = '貼文目錄'
 pageRef = '/posts'
 weight = 1

[module]
 [module.hugoVersion]
  extended = false
  min = "0.116.0"

